#!/bin/bash

# Copyright 2023 Matt Miller https://github.com/millermatt
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -e

getBrokerBindHost() {
    # Get the IP address using ifconfig
    IP=$(ifconfig | grep 'inet ' | grep -v '127.0.0.1' | grep -v '169.254.169.1' | awk '{print $2}')
    # If ifconfig didn't work, try using ip
    if [ -z "$IP" ]; then
        IP=$(ip addr show | grep 'inet ' | grep -v '127.0.0.1' | grep -v '169.254.169.1' | awk '{print $2}' | cut -d'/' -f1)
    fi
    IP="$(echo "$IP" | head -n 1)"
    echo "$IP"
}

# defaults
OS=$(uname)
if [[ $OS == "Linux" ]]; then
    DEFAULT_IMDS_SPOOF_PROXY_DOCKER_UPSTREAM=$(getBrokerBindHost)
    DEFAULT_IMDS_SPOOF_BROKER_HOST=$DEFAULT_IMDS_SPOOF_PROXY_DOCKER_UPSTREAM
else
    DEFAULT_IMDS_SPOOF_PROXY_DOCKER_UPSTREAM=host.docker.internal
    DEFAULT_IMDS_SPOOF_BROKER_HOST=127.0.0.1
fi
DEFAULT_IMDS_SPOOF_BROKER_COMMAND="node ./src/index.js"
DEFAULT_IMDS_SPOOF_BROKER_EXTERNAL_COMMAND="echo -n"
DEFAULT_IMDS_SPOOF_BROKER_FOLDER="$(dirname $0)/../imds-spoof-broker"
DEFAULT_IMDS_SPOOF_BROKER_PORT="5791"
DEFAULT_IMDS_SPOOF_PROXY_DOCKER_CONTAINER_NAME=imds-spoof-proxy
DEFAULT_IMDS_SPOOF_PROXY_DOCKER_IMAGE=nginx
DEFAULT_IMDS_SPOOF_PROXY_DOCKER_NETWORK_NAME=imds-spoof
DEFAULT_IMDS_SPOOF_PROXY_DOCKER_RUN_PARAMS="-e BROKER_HOST=$DEFAULT_IMDS_SPOOF_PROXY_DOCKER_UPSTREAM -e BROKER_PORT=$DEFAULT_IMDS_SPOOF_BROKER_PORT -v "$(realpath "$(dirname $0)")/config/imds-spoof-nginx.conf.template":/etc/nginx/templates/default.conf.template:ro"

# overrides
export IMDS_SPOOF_BROKER_COMMAND="${IMDS_SPOOF_BROKER_COMMAND-${DEFAULT_IMDS_SPOOF_BROKER_COMMAND}}"
export IMDS_SPOOF_BROKER_EXTERNAL_COMMAND="${IMDS_SPOOF_BROKER_EXTERNAL_COMMAND-${DEFAULT_IMDS_SPOOF_BROKER_EXTERNAL_COMMAND}}"
export IMDS_SPOOF_BROKER_FOLDER="${IMDS_SPOOF_BROKER_FOLDER-${DEFAULT_IMDS_SPOOF_BROKER_FOLDER}}"
export IMDS_SPOOF_BROKER_HOST="${IMDS_SPOOF_BROKER_HOST-${DEFAULT_IMDS_SPOOF_BROKER_HOST}}"
export IMDS_SPOOF_BROKER_PORT="${IMDS_SPOOF_BROKER_PORT-${DEFAULT_IMDS_SPOOF_BROKER_PORT}}"
export IMDS_SPOOF_PROXY_DOCKER_CONTAINER_NAME="${IMDS_SPOOF_PROXY_DOCKER_CONTAINER_NAME-${DEFAULT_IMDS_SPOOF_PROXY_DOCKER_CONTAINER_NAME}}"
export IMDS_SPOOF_PROXY_DOCKER_IMAGE="${IMDS_SPOOF_PROXY_DOCKER_IMAGE-${DEFAULT_IMDS_SPOOF_PROXY_DOCKER_IMAGE}}"
export IMDS_SPOOF_PROXY_DOCKER_NETWORK_NAME="${IMDS_SPOOF_PROXY_DOCKER_NETWORK_NAME-${DEFAULT_IMDS_SPOOF_PROXY_DOCKER_NETWORK_NAME}}"
export IMDS_SPOOF_PROXY_DOCKER_RUN_PARAMS="${IMDS_SPOOF_PROXY_DOCKER_RUN_PARAMS-${DEFAULT_IMDS_SPOOF_PROXY_DOCKER_RUN_PARAMS}}"


COMMAND=$1
COMMAND_PATH="`dirname $0`/commands/${COMMAND}"

if [[ -f "$COMMAND_PATH" ]]; then
    shift
    eval "$COMMAND_PATH $@"
else
    echo "error: invalid command" >/dev/stderr
    exit 1
fi
