#!/bin/bash

# Copyright 2023 Matt Miller https://github.com/millermatt
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# these lines allow `set -u` (no undefined variables) to work for the rest of the script
export IMDS_SPOOF_BROKER_COMMAND=$IMDS_SPOOF_BROKER_COMMAND
export IMDS_SPOOF_BROKER_FOLDER=$IMDS_SPOOF_BROKER_FOLDER
export IMDS_SPOOF_BROKER_HOST=$IMDS_SPOOF_BROKER_HOST
export IMDS_SPOOF_BROKER_PORT=$IMDS_SPOOF_BROKER_PORT

set -eu

source "$(dirname $0)/../util/broker-ctl"

stopBroker
sleep 1
clearBrokerLogs
startBroker
