#!/bin/bash

# these lines allow `set -u` (no undefined variables) to work for the rest of the script
export IMDS_SPOOF_BROKER_COMMAND=$IMDS_SPOOF_BROKER_COMMAND
export IMDS_SPOOF_BROKER_FOLDER=$IMDS_SPOOF_BROKER_FOLDER
export IMDS_SPOOF_BROKER_HOST=$IMDS_SPOOF_BROKER_HOST
export IMDS_SPOOF_BROKER_PORT=$IMDS_SPOOF_BROKER_PORT

set -eu

source "$(dirname $0)/../util/broker-ctl"

stopBroker
sleep 1
clearBrokerLogs
startBroker
