#!/bin/bash

# Copyright 2023 Matt Miller https://github.com/millermatt
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# these lines allow `set -u` (no undefined variables) to work for the rest of the script
export IMDS_SPOOF_PROXY_DOCKER_NETWORK_NAME=$IMDS_SPOOF_PROXY_DOCKER_NETWORK_NAME
export IMDS_SPOOF_PROXY_DOCKER_CONTAINER_NAME=$IMDS_SPOOF_PROXY_DOCKER_CONTAINER_NAME
export IMDS_SPOOF_BROKER_COMMAND=$IMDS_SPOOF_BROKER_COMMAND
export IMDS_SPOOF_BROKER_FOLDER=$IMDS_SPOOF_BROKER_FOLDER

set -eu

source "$(dirname $0)/../util/broker-ctl"

stopDockerNetwork() {
  if [[ "$(docker network list --format '{{.Name}}' | grep "^${IMDS_SPOOF_PROXY_DOCKER_NETWORK_NAME}$")" != "" ]]; then
    if [[ !$(docker network rm $IMDS_SPOOF_PROXY_DOCKER_NETWORK_NAME >/dev/null 2>&1) ]]; then
      echo "Could not stop Docker network '$IMDS_SPOOF_PROXY_DOCKER_NETWORK_NAME'" >/dev/stderr
      echo "Containers connected to the network:" >/dev/stderr
      local connected_containers="$(docker network inspect $IMDS_SPOOF_PROXY_DOCKER_NETWORK_NAME -f '{{range $id, $container := .Containers}}{{$container.Name}} {{end}}')"
      # trim trailing whitespace
      connected_containers="$(echo "$connected_containers" | xargs)"
      echo "$connected_containers" | tr ' ' '\n' | sed -e 's/^/  - /'
      return 1
    fi
  fi
}

stopProxy() {
  local running_proxy_container_json=`docker container inspect $IMDS_SPOOF_PROXY_DOCKER_CONTAINER_NAME 2>/dev/null`
  if [[ "$running_proxy_container_json" != "[]" ]]; then
    docker container stop $IMDS_SPOOF_PROXY_DOCKER_CONTAINER_NAME >/dev/null 2>&1
  fi
}

stopBroker
stopProxy
stopDockerNetwork
